export const tiposDeResidencia = [
   "Casa",
   "Apartamento",
   "Sobrado",
   "Chalé",
   "Cobertura",
   "Kitnet",
   "Flat",
   "Loft",
   "Bangalô",
   "Quitinete",
   "Edícula",
   "Casa de Campo",
   "Casa de Praia",
   "Barracão",
   "Casa Geminada",
   "Casa em Condomínio",
   "Apartamento Duplex",
   "Apartamento Triplex",
   "Casa Colonial",
   "Vila",
   "Cabana",
   "Casarão",
   "Mansão",
   "Iglu",
   "Casa Sustentável",
   "Casinha de Boneca",
   "Tenda",
   "Estúdio",
   "República",
   "Residencial Universitário"
];

export const tiposDeLogradouro = [
   "Avenida",
   "Rua",
   "Alameda",
   "Travessa",
   "Estrada",
   "Praça",
   "Viaduto",
   "Largo",
   "Rodovia",
   "Beco",
   "Ladeira",
   "Passarela",
   "Parque",
   "Jardim",
   "Via",
   "Vereda",
   "Caminho",
   "Passeio",
   "Calçadão",
   "Elevada",
   "Acostamento",
   "Ramal",
   "Cais",
   "Bulevar",
   "Quarteirão",
   "Rotatória",
   "Travessia",
   "Rampa",
   "Marginal",
   "Loteamento",
   "Trevo",
   "Acesso",
   "Ciclovia"
];